[Fix] Calcular Data Final do Holerite = Data do Afastamento para Resc…
kmee/odoo-brazil-hr pull request #110
Opened 2017-06-21 12:04 UTC by wagnerpereirasp

Levar em consideração a data de afastamento como data final do holerite de rescisão.

2017-06-21 12:56 UTC, Hendrixcosta commented
Apesar de setar a data final do holerite corretamente, os dias trabalhados continua não funcionando. =\

2017-06-21 12:57 UTC, hendrixcosta requested changes

2017-06-21 12:57 UTC, Hendrixcosta commented on l10n_br_hr_payroll/models/hr_payslip.py
> +
@wagnerpereirasp Sugiro colocar o campo 'data_afastamento' no depends da função, assim quando o usuario alterar a data de afastamento, a data final do holerite se alterara ao mesmo tempo.

" @api.depends('mes_do_ano', 'ano', 'holidays_ferias', 'data_afastamento')"

2017-06-21 13:12 UTC, wagnerpereirasp commented on l10n_br_hr_payroll/models/hr_payslip.py
> +
Feito exatamente como sugerido. Valeu!

2017-06-21 13:58 UTC, hendrixcosta approved these changes

2017-06-21 13:59 UTC, hendrixcosta submitted a review, later dismissed
Apesar de setar a data final do holerite corretamente, os dias trabalhados continua não funcionando. =\

2017-06-22 18:06 UTC, Hendrixcosta commented
@wagnerpereirasp Dessa forma a contabilização dos dias trabalhados parece funcionar, mas no holerite que esta sendo calculado não deveria mostrar o date_to com a data da rescisão?

2017-06-23 12:02 UTC, wagnerpereirasp commented
Revisado cálculo da data final do holerite de rescisão para data do afastamento - 1, para recalcular o holerite é necessário clicar no botão "Calcular" manualmente, isso é feito por design.

2017-06-23 13:58 UTC, lfdivino approved these changes

2017-06-23 13:59 UTC, merged