Feature/ordem pagamento
kmee/odoo-brazil-hr pull request #128
Opened 2017-07-10 20:52 UTC by lfdivino

2017-07-14 11:16 UTC, Hendrixcosta commented on l10n_br_hr_payment_order/views/hr_payslip.xml
> +                <button name="action_done" type="object"
Esses buttons não estão duplicados?

2017-07-14 11:18 UTC, Hendrixcosta commented on l10n_br_hr_payment_order/models/payment_order.py
> -class PaymentOrder(models.Model):
Arquivo tem que ter nome do modelo implementado na classe.

2017-07-18 18:58 UTC, mileo requested changes

2017-07-18 18:58 UTC, mileo commented on l10n_br_hr_payment_order/models/hr_payslip.py
> +            # 'partner_bank_id': self.partner_bank_id.id,
Isto esta correto?

2017-07-18 18:58 UTC, mileo commented on l10n_br_hr_payment_order/models/hr_payslip.py
> +                ('state', '=', 'draft')]
Estado incorreto

2017-07-18 18:58 UTC, mileo commented on l10n_br_hr_payment_order/views/hr_contract.xml
> +</openerp>
New Line

2017-07-19 18:25 UTC, Hendrixcosta commented on l10n_br_hr_payment_order/models/hr_payslip.py
> +                ('state', '=', 'draft')]
Busca das payment_order que estão em aberto. Estado é draft mesmo

2017-07-19 18:26 UTC, Hendrixcosta commented on l10n_br_hr_payment_order/models/hr_payslip.py
> +            # 'partner_bank_id': self.partner_bank_id.id,
Feito Ajuste.

2017-07-20 20:38 UTC, Hendrixcosta commented
@wagnerpereirasp por favor estabilize o travis

2017-07-20 21:35 UTC, mileo approved these changes

2017-07-20 22:12 UTC, merged