Feature/workflow sefip caged
kmee/odoo-brazil-hr pull request #129
Opened 2017-07-11 15:09 UTC by sadamo

2017-07-11 15:21 UTC, wagnerpereirasp reviewed
Sadamo, tira os print dos arquivos.

2017-07-11 18:21 UTC, sadamo commented
@wagnerpereirasp, eu já tinha tirado no próximo commit, por isso que vc não tinha achado naquela aba "View FIles"

2017-07-18 14:10 UTC, lfdivino commented
@sadamo Arrumar por favor os problemas de pep8

2017-07-18 14:11 UTC, lfdivino requested changes

2017-07-18 14:11 UTC, lfdivino commented on l10n_br_hr_arquivos_governo/views/l10n_br_hr_sefip.xml
> +                <div class="oe_chatter">
@sadamo Tudo na página precisa ficar dentro do <form></form> na view, senão da erro de organização da view

2017-07-18 14:11 UTC, lfdivino commented on l10n_br_hr_arquivos_governo/views/l10n_br_hr_caged.xml
> +                <div class="oe_chatter">
@sadamo Tudo na página precisa ficar dentro do <form></form> na view, senão da erro de organização da view

2017-07-18 18:59 UTC, lfdivino approved these changes

2017-07-19 21:26 UTC, merged